spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:test
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true      # (2) SQL 쿼리 출력
    properties:
      hibernate:
        format_sql: true  # (3) SQL pretty print
        highlight_sql: true
        color-codes: true
        use_sql_comments: true
    defer-datasource-initialization: true # 더미데이터 전 테이블 부터 만듦


  sql:
    init:
      data-locations: classpath*:db/h2/data.sql # 더미데이터
      mode: always # 더미데이터 관련
      platform: h2
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: ${G_CLIENT_ID}
            clientSecret: ${G_CLIENT_SECRET}
            redirect-uri: https://040e-124-111-225-247.ngrok-free.app/login/oauth2/code/google # 이건 주소 바뀔때마다 수정해야함
            scope:
              - email
              - profile
          facebook:
            client-id: ${F_CLIENT_ID}
            client-secret: ${F_CLIENT_SECRET}
            scope:
              - email
              - public_profile
#          naver:
#            client-id: ${N_CLIENT_ID}
#            client-secret: ${N_CLIENT_SECRET}
#            scope:
#              - name
#              - email
#            redirect-uri: http://localhost:8080/login/oauth2/code/naver
#            authorization-grant-type: authorization_code
#            client-name: Naver
          kakao:
            client-id: 7c67eb4ba631e8116081b968377e35d6
            client-secret: NWGmTyHL3wzQB2SdDDYAAeJdEmtom3Lw
            redirect-uri: https://9b00-124-111-225-247.ngrok-free.app/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            client-name: Kakao
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
#            naver:
#              authorization-uri: https://nid.naver.com/oauth2.0/authorize
#              token-uri: https://nid.naver.com/oauth2.0/token
#              user-info-uri: https://openapi.naver.com/v1/nid/me
#              user-name-attribute: response




logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace;
      springframework:
        orm:
          jpa: DEBUG

mail:
  address:
    admin: admin@gmail.com
  smtp:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME}  # 민감한 정보는 시스템 환경 변수로..
    password: ${EMAIL_PASSWORD}  # 민감한 정보는 시스템 환경 변수로..
    auth: true
    starttls:
      enable: true
  subject:
    member:
      registration: 매주매주 가입 축하해요!
  template:
    name:
      member:
        join: email-registration-member

server:
  servlet:
    encoding:
      force-response: true


jwt:
  key: ${JWT_SECRET_KEY}
  access-token-expiration-minutes: 30 #30분.
  refresh-token-expiration-minutes: 420 # 420분

cloud:
  aws:
    credentials.access-key: ${S3_ACCESS_KEY}
    credentials.secret-key: ${S3_SECRET_KEY}
    s3.bucket: jusinsa.kr
    region.static: ap-northeast-2
    stack.auto: false