spring:
  datasource:
    url: jdbc:mysql://mejujjin.cqjqdmoev447.ap-northeast-2.rds.amazonaws.com:13306/JJIN?useSSL=false&characterEncoding=UTF-8&serve
    username: admin
    password: qwer1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  config:
    domain: http://codestates-main-mejumeju.s3-website.ap-northeast-2.amazonaws.com/
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    show-sql: true      # (2) SQL 쿼리 출력
    properties:
      hibernate:
        format_sql: true  # (3) SQL pretty print
        highlight_sql: true
        color-codes: true
        use_sql_comments: true
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 911444161086-3src60dn7goa37hqthsh1u1omvk5gil5.apps.googleusercontent.com
            clientSecret: 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
            redirect-uri: http://ec2-13-124-60-159.ap-northeast-2.compute.amazonaws.com:8080/login/oauth2/code/google  # 이건 주소 바뀔때마다 수정해야함
            scope:
              - email
              - profile
          facebook:
            client-id: 192664940391580
            client-secret: 2924e285e2333cd422f060e21a2f31a5
            redirect-uri: http://ec2-13-124-60-159.ap-northeast-2.compute.amazonaws.com:8080/login/oauth2/code/facebook
            scope:
              - email
              - public_profile

          kakao:
            client-id: 7c67eb4ba631e8116081b968377e35d6
            client-secret: NWGmTyHL3wzQB2SdDDYAAeJdEmtom3Lw
            redirect-uri: http://ec2-13-124-60-159.ap-northeast-2.compute.amazonaws.com:8080/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            client-name: Kakao
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id


logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace;
      springframework:
        orm:
          jpa: DEBUG

mail:
  address:
    admin: admin@gmail.com
  smtp:
    host: smtp.gmail.com
    port: 587
    username: ku3026@gmail.com  # 민감한 정보는 시스템 환경 변수로..
    password: fcsnjwkqwbmqbjbu  # 민감한 정보는 시스템 환경 변수로..
    auth: true
    starttls:
      enable: true
  subject:
    member:
      registration: 매주매주 가입 축하해요!
  template:
    name:
      member:
        join: email-registration-member

server:
  servlet:
    encoding:
      force-response: true


jwt:
  key: kevin12341234123412341234123412341234123412341234123412341234
  access-token-expiration-minutes: 30 #30분.
  refresh-token-expiration-minutes: 420 # 420분

cloud:
  aws:
    credentials.access-key: AKIAW5A3TF4PZMEILIEF
    credentials.secret-key: 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
    s3.bucket: codepipeline-ap-northeast-2-434800846642
    region.static: ap-northeast-2
    stack.auto: false

toss:
  secret-key: test_sk_YoEjb0gm23P1O1BQ7WgVpGwBJn5e


